In [3]:
import pandas as pd 
import numpy as np

In [9]:
#Object creation

obj = pd.Series([1,2,3,4,5,6,7,8,9])
obj

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [17]:
dates= pd.date_range("20220101", periods=31)
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
               '2022-01-29', '2022-01-30', '2022-01-31'],
              dtype='datetime64[ns]', freq='D')

In [18]:
#create dataframe from the above dates
df =pd.DataFrame(np.random.randn(31,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2022-01-01 -0.974139 -0.396395  1.544147 -0.701130
2022-01-02 -1.704205  0.977225  0.223256  0.063063
2022-01-03 -0.600055 -0.379111  0.837169 -1.105371
2022-01-04  0.063032  1.792947 -0.035839  0.750574
2022-01-05  0.849517  0.776217  0.121757 -2.381314
2022-01-06  0.103773 -0.174456  0.777830 -1.135462
2022-01-07  1.005812 -0.578340 -1.626904 -0.626425
2022-01-08 -0.921640  1.201837 -0.980377 -0.553443
2022-01-09 -0.506840  1.143853  1.447829 -0.669139
2022-01-10 -0.165086  0.915886 -0.194795  1.275387
2022-01-11  0.186829 -0.903268 -0.269967  0.917620
2022-01-12 -1.960130 -1.032743 -0.312269  0.790344
2022-01-13  0.899174  0.593036  2.083091  0.391954
2022-01-14  0.179078 -0.261001  0.176807  1.149599
2022-01-15 -1.515029  0.929340  0.357705 -0.171261
2022-01-16 -0.730699  0.406512  1.770811 -1.120056
2022-01-17  1.572643 -0.613921 -0.221452  0.681680
2022-01-18  0.183165 -0.725558 -1.066908 -0.955867
2022-01-19  1.118827 -1.745276 -0.104561  0.646390
2022-01-20 -0.932731 -2.112818  0.172512  1.079534
2022-01-21  1.224524 -0.130998  0.531775  0.929347
2022-01-22  1.146547 -1.228359 -0.196485  1.690498
2022-01-23 -0.286932  0.232077 -0.607538  0.538189
2022-01-24  0.801066  0.965914 -1.251903 -2.712421
2022-01-25 -0.109280 -0.497643 -0.620787 -1.822372
2022-01-26  0.157270 -0.009646 -1.445588 -0.284782
2022-01-27  1.216182 -1.251357  1.149964  0.274713
2022-01-28 -0.996427 -0.251540  1.107585  0.512337
2022-01-29  0.529741 -1.090606  0.256019  1.222516
2022-01-30  0.048874 -0.794473  0.577320 -1.630310
2022-01-31 -2.174994  0.446672 -1.388026 -0.998271